/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EntrarImport } from './routes/entrar'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as CadastrarAutoImport } from './routes/cadastrar-auto'
import { Route as CadastrarImport } from './routes/cadastrar'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const PoliticaPrivacidadeLazyImport = createFileRoute('/politica-privacidade')()

// Create/Update Routes

const PoliticaPrivacidadeLazyRoute = PoliticaPrivacidadeLazyImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/politica-privacidade.lazy').then((d) => d.Route),
)

const EntrarRoute = EntrarImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CadastrarAutoRoute = CadastrarAutoImport.update({
  id: '/cadastrar-auto',
  path: '/cadastrar-auto',
  getParentRoute: () => rootRoute,
} as any)

const CadastrarRoute = CadastrarImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarImport
      parentRoute: typeof rootRoute
    }
    '/cadastrar-auto': {
      id: '/cadastrar-auto'
      path: '/cadastrar-auto'
      fullPath: '/cadastrar-auto'
      preLoaderRoute: typeof CadastrarAutoImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarImport
      parentRoute: typeof rootRoute
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastrar-auto': typeof CadastrarAutoRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastrar-auto': typeof CadastrarAutoRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastrar-auto': typeof CadastrarAutoRoute
  '/dashboard': typeof DashboardRoute
  '/entrar': typeof EntrarRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar'
    | '/cadastrar-auto'
    | '/dashboard'
    | '/entrar'
    | '/politica-privacidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar'
    | '/cadastrar-auto'
    | '/dashboard'
    | '/entrar'
    | '/politica-privacidade'
  id:
    | '__root__'
    | '/'
    | '/cadastrar'
    | '/cadastrar-auto'
    | '/dashboard'
    | '/entrar'
    | '/politica-privacidade'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  CadastrarAutoRoute: typeof CadastrarAutoRoute
  DashboardRoute: typeof DashboardRoute
  EntrarRoute: typeof EntrarRoute
  PoliticaPrivacidadeLazyRoute: typeof PoliticaPrivacidadeLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  CadastrarAutoRoute: CadastrarAutoRoute,
  DashboardRoute: DashboardRoute,
  EntrarRoute: EntrarRoute,
  PoliticaPrivacidadeLazyRoute: PoliticaPrivacidadeLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cadastrar",
        "/cadastrar-auto",
        "/dashboard",
        "/entrar",
        "/politica-privacidade"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cadastrar": {
      "filePath": "cadastrar.tsx"
    },
    "/cadastrar-auto": {
      "filePath": "cadastrar-auto.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/entrar": {
      "filePath": "entrar.tsx"
    },
    "/politica-privacidade": {
      "filePath": "politica-privacidade.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
